version: "3.8"

services:
  caisse-app:
    build: .
    container_name: caisse-magasin-client
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_URL: postgresql://user:password@10.194.32.219:5432/store_db
      POOL_SIZE: 5
      MAX_OVERFLOW: 10